SET IDENTITY_INSERT [dbo].[Curriculum] ON
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [SchoolId]) VALUES (1, N'cycle ingenieur efrei', 3, 1, N'Informatique', 1, 1, 1)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (2, N'cycle ingenieur esiee', 3, 1, N'Informatique', 1, 1, 1, 2)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (3, N'info iut orsay ', 2, 1, N'Informatique', 0, 1, 0, 3)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (4, N'BTS esiee', 2, 1, N'Informatique', 0, 1,1, 2)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (5, N'licence info universite sorbonne', 3, 1, N'Informatique', 1, 1, 0, 4)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (6, N'licence math info universite paris nanterre', 3, 1, N'Informatique', 0, 1,1, 5)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (7, N'cycle ingenieur ESIEA', 3, 1, N'Informatique', 1, 1, 0, 6)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (8, N'cycle ingenieur ESILV', 3, 1, N'Informatique', 1, 1, 1, 7)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (9, N'cycle ingenieur ISEP', 3, 1, N'Informatique', 1, 1, 0, 8)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (10, N'info iut Villetaneuse', 2, 1, N'Informatique', 0, 1, 1, 9)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (11, N'licence info Universite sorbonne paris nord', 3, 1, N'Informatique', 0, 1, 0, 9)
INSERT INTO [dbo].[Curriculum] ([CurriculumId], [Name], [Duration], [AdmissionType], [Domain], [IsApprenticeship], [IsInitialFormation], [StateRecognition], [SchoolId]) VALUES (12, N'cycle ingenieur ECE', 3, 1, N'Informatique', 1, 1, 1, 10)
SET IDENTITY_INSERT [dbo].[Curriculum] OFF