
SET IDENTITY_INSERT [dbo].[School] ON
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (1, N'EFREI PARIS', 1, N'30-32 Av. de la République, 94800 Villejuif, Val-de-Marne, Ile-de-France', N'https://www.efrei.fr/', 1, 40000, N'Villejuif', 1, 94800)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (2, N'ESIEE PARIS', 1, N'2 boulevard Blaise Pascal, 93162 Noisy-le-Grand, Seine-Saint-Denis, Ile-de-France', N'https://www.esiee.fr/en', 1, 40000, N'Noisy-le-Grand', 0, 93162)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (3, N'Université Paris-Saclay', 1, N'3 rue Joliot Curie, 91190 Gif-sur-Yvette, Essonne, Ile-de-France', N'https://www.universite-paris-saclay.fr/en', 0, 35000, N'Gif-sur-Yvette', 1, 91190)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (4, N'Sorbonne Université', 1, N'21 rue de l’École de médecine, 75006 Paris, Ile-de-France', N'https://www.sorbonne-universite.fr/en', 0, 35000, N'Paris', 1, 75006)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (5, N'Université Paris Nanterre', 1, N'200 avenue de la République, 92001 Nanterre, Hauts-de-Seine, Ile-de-France ', N'https://university.parisnanterre.fr/', 0, 35000, N'Nanterre', 1, 92001)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (6, N'ESIA', 1, N'9 rue Vesale, 75005 Paris, Ile-de-France', N'https://en.esiea.fr/', 1, 40000, N'Paris', 0, 75005)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (7, N'ESILV', 1, N'12 AVENUE LÉONARD DE VINCI, 92916 Courbevoie, Hauts-de-Seine, Ile-de-France', N'https://www.esilv.fr/en/', 1, 40000, N'Courbevoie', 0, 92916)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (8, N'ISEP', 1, N'28 rue Notre-Dame-des-Champs, 75006 Paris, Ile-de-France ', N'https://en.isep.fr/', 1, 40000, N'Paris', 0, 75006)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (9, N'Université Sorbonne Paris Nord', 1, N'99 avenue Jean-Baptiste Clément, 93430 Villetaneuse, Seine-Saint-Denis, Ile-de-France', NULL, 0, 35000, N'Villetaneuse', 1, 93430)
INSERT INTO [dbo].[School] ([SchoolId], [Name], [InsertionRate], [Address], [Website], [IsPrivate], [AverageSalary], [City], [IsPublic], [ZipCode]) VALUES (10, N'ECE', 1, N'37 quai de Grenelle, 75015 Paris, Ile-de-France', NULL, 1, 35000, N'Paris', 0, 75015)
SET IDENTITY_INSERT [dbo].[School] OFF